#!/bin/bash

####
# This script is used for an Extension Attribute and checks for the Configuration Profiles on a machine
#Replace Test with name of configuration profile
# By Zach Andreae
# 6/22/23
####

# Check if the "Test" configuration profile is installed
profile_name="Test"
profile_found="No"

# Get the list of installed configuration profiles using 'profiles' command
installed_profiles=$(profiles -Cv)

# Check if the profile_name exists in the list of installed profiles
if grep -q "$profile_name" <<< "$installed_profiles"; then
    profile_found="Yes"
fi

# Output the result
echo "'Test' configuration profile installed? $profile_found"
